export type PageType = "digital" | "scanned";

export interface ExtractedValue {
  value: string;
  source: "pymupdf" | "paddleocr" | "tesseract";
  confidence: number;
  page: number;
  bbox: [number, number, number, number];
}

export interface BoqField {
  value: string;
  source: "pymupdf" | "paddleocr" | "tesseract";
  confidence: number;
  page: number;
  bbox: [number, number, number, number];
  status?: "valid" | "review" | "ambiguous";
  rules_triggered?: string[];
}

export interface BoqRow {
  description: BoqField;
  quantity: BoqField;
  unit: BoqField;
  rate: BoqField;
  amount: BoqField;
  status: "valid" | "review" | "ambiguous";
  rules_triggered?: string[];
}

export interface ProcessResult {
  document_id: string;
  document_type: string;
  pages_processed: number;
  status: string;
  summary: {
    total_rows: number;
    valid_rows: number;
    review_rows: number;
    llm_normalized_fields: number;
  };
  boq: BoqRow[];
}

export type SelectedSource =
  | { type: "sample"; file: string }
  | { type: "upload"; file: File };

export interface UploadResponse {
  documentId: string;
  filename: string;
  status: "uploaded";
}

// Precomputed (real router output) at dev-time for the 3 bundled samples —
// see lib/sample-metadata.json, generated by running inspect_document()
// directly against public/samples/*.pdf.
export interface SampleMetadata {
  pages: PageRoute[];
  digitalCount: number;
  scannedCount: number;
  thumbnail: string;
}

export interface PageRoute {
  page: number;
  type: PageType;
}

export interface PrepareResult {
  document_id: string;
  pages: PageRoute[];
}

// One entry per page in results/<id>/regions.json. `regions` shape differs
// by branch: digital pages hold ExtractedValue-shaped PyMuPDF text blocks,
// scanned pages hold PP-StructureV3 layout regions ({type, bbox, category}).
export interface PageRegionsEntry {
  page: number;
  type: PageType;
  width: number;
  height: number;
  regions: Array<Record<string, unknown>>;
}
